### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by wolflingorg** [AnnBond/Epam-Mentoring#1]
- тут https://github.com/AnnBond/Epam-Mentoring/blob/master/Beginnings/task4.php#L14 замени пожалуйста echo на short echo `<?=`. Пример: ```Value is now <?= $variable ?>.</br>``` - т.е. строка - это html, php только там, где переменные
 - чем запись ```echo "Add 2. Value is now " . ($variable += 2) . ".</br>";``` отличается от ```echo "Add 2. Value is now " . ($variable + 2) . ".</br>";```?

**Comment by AnnBond** [comment]
я не бачу цієї стрічки в своєму коді echo "Add 2. Value is now " . ($variable + 2) . ".</br>"

**Comment by AnnBond** [comment]
а відрізняєтся тим що в першому варіанті значення змінної перезаписуєтся
