### ISSUE TITLE
Идеи к размышлению

### ISSUE THREAD

**Issue by wolflingorg** [AnnBond/Epam-Mentoring#3]
- тут https://github.com/AnnBond/Epam-Mentoring/blob/master/ControlStructures/task1.php#L12 ты использовала флаг 'F' для отображение текущего месяца в текстовом виде. В документации http://php.net/manual/en/function.date.php можно найти другие флаги. Для практики, можешь заменить флаг 'F' на что-то другое, к примеру, на номер месяца.

 - тут https://github.com/AnnBond/Epam-Mentoring/blob/master/ControlStructures/task1.php#L14 использовала двлйное равно. Чем оно отличается от тройного?

 - for с двумя переменными тут https://github.com/AnnBond/Epam-Mentoring/blob/master/ControlStructures/task2.php#L28 круто! правда я не разу не видел, на практике, чтобы так юсали ;)

 - тут https://github.com/AnnBond/Epam-Mentoring/blob/master/ControlStructures/task4.php#L26 по аналогии с Олей, для практики попробуй заменить **echo** на short echo и альтернативную запись уиклов: https://github.com/OlgaKlekot/EPAM-PHP-mentee/issues/3

**Comment by AnnBond** [comment]
знаки рівності відрізняються тим, що == не строга рівність(тобто типи даних можуть бути різні), а при === порівнювані дані мають бути однакових типів.

**Comment by AnnBond** [comment]
all done

**Comment by wolflingorg** [comment]
Супер!
