### ISSUE TITLE
К размышлению

### ISSUE THREAD

**Issue by wolflingorg** [AnnBond/Epam-Mentoring#4]
- тут https://github.com/AnnBond/Epam-Mentoring/blob/master/Forms/Task1/request.php#L2 перед тем, как обращаться к $_POST['yourCity'] желательно проверить, а в массиве POST такой ключ вообще существует? Тут, такая проверка есть https://github.com/AnnBond/Epam-Mentoring/blob/master/Forms/task2.php#L12 =) Посмотри разницу между isset, empty и array_key_exists

**Comment by AnnBond** [comment]
Почитала і додала перевірку)
