### ISSUE TITLE
lets go

### ISSUE THREAD

**Issue by Zlangobelz** [AnnBond/Epam-Mentoring#5]
https://github.com/AnnBond/Epam-Mentoring/blob/master/Forms/Task1/request.php - ти спочатку присвоюєш змінній значення з масиву а потім перевіряєш чи це значення існує, зроби навпаки.
https://github.com/AnnBond/Epam-Mentoring/blob/master/Forms/task4.php - як на мене, простіше би було замість 3 рядків коду кнопки "Come back" зробити ссилку на головну сторінку.

**Comment by AnnBond** [comment]
Done
